site:
  name: Robert Ferguson
  site: 'https://rewferguson.com'
  base: '/'
  trailingSlash: false

  # googleSiteVerificationId: ###

# Default SEO metadata
metadata:
  title:
    default: Robert Ferguson
    template: '%s — Robert Ferguson'
  description: 'A personal site for Robert Ferguson, a software engineer and creative maker.'
  robots:
    index: true
    follow: true
  openGraph:
    site_name: Robert Ferguson
    images:
      - url: '~/assets/images/default.png'
        width: 1200
        height: 628
    type: website

i18n:
  language: en
  textDirection: ltr

apps:
  blog:
    isEnabled: true
    postsPerPage: 6

    post:
      isEnabled: true
      permalink: '/%slug%' # Variables: %slug%, %year%, %month%, %day%, %hour%, %minute%, %second%, %category%
      robots:
        index: true

    list:
      isEnabled: true
      pathname: 'blog' # Blog main path, you can change this to "articles" (/articles)
      robots:
        index: true

    category:
      isEnabled: true
      pathname: 'category' # Category main path /category/some-category, you can change this to "group" (/group/some-category)
      robots:
        index: true

    tag:
      isEnabled: true
      pathname: 'tag' # Tag main path /tag/some-tag, you can change this to "topics" (/topics/some-category)
      robots:
        index: false

    isRelatedPostsEnabled: true
    relatedPostsCount: 4

analytics:
  vendors:
    googleAnalytics:
      id: 'G-5BJF2PLFNV'

ui:
  theme: 'system' # Values: "system" | "light" | "dark" | "light:only" | "dark:only"

  tokens:
    default:
      fonts:
        sans: MontserratVariable
        serif: MontserratVariable
        heading: MontserratVariable
      colors:
        default: rgb(16 16 16)
        dark: rgb(3 6 32)
        heading: rgb(0 0 0)
        muted: rgb(16 16 16 / 66%)
        bgPage: rgb(255 255 255)
        primary: rgb(30 50 90)
        secondary: rgb(88 139 202)
        accent: rgb(224 0 110)
    dark:
      fonts: {}
      colors:
        default: rgb(229 236 246)
        dark: hsl(198 74% 20% / 1)
        heading: rgb(247, 248, 248)
        muted: rgb(229 236 246 / 66%)
        bgPage: hsl(198 74% 20% / 1)
        # primary: rgb(88 139 202)
        primary: rgb(88 187 202)
        # secondary: rgb(88 202 145)
        accent: rgb(88 202 149)
        secondary: rgb(224 0 110)
        # secondary: hsl(181 70% 31% / 1)
